export const ADD_ITEM_TO_INVENTORY = 'ADD_ITEM_TO_INVENTORY';
export const START_FETCHING_INV_ITEMS = 'START_FETCHING_INV_ITEMS';
export const SUCCESS_FETCHING_INV_ITEMS = 'SUCCESS_FETCHING_INV_ITEMS';
export const FAILURE_FETCHING_INV_ITEMS = 'FAILURE_FETCHING_INV_ITEMS';
export const UPDATE_INV_ITEM = 'UPDATE_INV_ITEM';
