export const ADD_ITEM_TO_INVENTORY = 'ADD_ITEM_TO_INVENTORY';
export const START_FETCHING_INV_ITEMS = 'START_FETCHING_INV_ITEMS';
export const SUCCESS_FETCHING_INV_ITEMS = 'SUCCESS_FETCHING_INV_ITEMS';
export const FAILURE_FETCHING_INV_ITEMS = 'FAILURE_FETCHING_INV_ITEMS';
export const UPDATE_INV_ITEM = 'UPDATE_INV_ITEM';
export const DELETE_INV_ITEM = 'DELETE_INV_ITEM';


export const NOTIFICATION_FETCH_STARTED = 'NOTIFICATION_FETCH_STARTED';
export const NOTIFICATION_FETCH_ERROR = 'NOTIFICATION_FETCH_ERROR';
export const NOTIFICATION_FETCH_SUCCESS = 'NOTIFICATION_FETCH_SUCCESS';
export const DELETE_EXPIRED_ITEM = 'DELETE_EXPIRED_ITEM';
export const UPDATE_EXPIRED_ITEM = 'UPDATE_EXPIRED_ITEM';

